<nav>
            <a href="index.html"><img src="Images/logo.jpeg" alt="Pets Victoria Logo"></a>
            <select id="pageSelector" onchange="navigateToPage()">
                <option value="https://jupiter.csit.rmit.edu.au/~s4094165/wp/a1/index.html" selected>Select an option</option>
                <option value="https://jupiter.csit.rmit.edu.au/~s4094165/wp/a1/index.html">Home</option>
                <option value="https://jupiter.csit.rmit.edu.au/~s4094165/wp/a1/pets.html">Pets</option>
                <option value="https://jupiter.csit.rmit.edu.au/~s4094165/wp/a1/add.html">Add More</option>
                <option value="https://jupiter.csit.rmit.edu.au/~s4094165/wp/a1/gallery.html">Gallery</option>
            </select>
            <form>
                <input type="text" placeholder="Search...">
                <button type="submit" class="search-button">
                    <span class="material-icons">search</span>
                </button>
            </form>
        </nav>
        