<nav>
            <a href="index.html"><img src="Images/logo.jpeg" alt="Pets Victoria Logo"></a>
            <select id="pageSelector" onchange="navigateToPage()">
                <option value="https://jupiter.csit.rmit.edu.au/~s4094165/wp/a2/index.php" selected>Select an option</option>
                <option value="https://jupiter.csit.rmit.edu.au/~s4094165/wp/a2/index.php">Home</option>
                <option value="https://jupiter.csit.rmit.edu.au/~s4094165/wp/a2/pets.php">Pets</option>
                <option value="https://jupiter.csit.rmit.edu.au/~s4094165/wp/a2/add.php">Add More</option>
                <option value="https://jupiter.csit.rmit.edu.au/~s4094165/wp/a2/gallery.php">Gallery</option>
            </select>
            <form>
                <input type="text" placeholder="Search...">
                <button type="submit" class="search-button">
                    <span class="material-icons">search</span>
                </button>
            </form>
        </nav>
        